// megafunction wizard: %LPM_ADD_SUB%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: LPM_ADD_SUB 

// ============================================================
// File Name: addfix8.v
// Megafunction Name(s):
// 			LPM_ADD_SUB
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 17.1.0 Build 590 10/25/2017 SJ Standard Edition
// ************************************************************


//Copyright (C) 2017  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel FPGA IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Intel and sold by Intel or its authorized distributors.  Please
//refer to the applicable agreement for further details.


//lpm_add_sub DEVICE_FAMILY="Stratix V" LPM_DIRECTION="ADD" LPM_PIPELINE=2 LPM_REPRESENTATION="SIGNED" LPM_WIDTH=64 ONE_INPUT_IS_CONSTANT="NO" clock dataa datab result
//VERSION_BEGIN 17.1 cbx_cycloneii 2017:10:25:18:06:53:SJ cbx_lpm_add_sub 2017:10:25:18:06:53:SJ cbx_mgl 2017:10:25:18:08:29:SJ cbx_nadder 2017:10:25:18:06:53:SJ cbx_stratix 2017:10:25:18:06:53:SJ cbx_stratixii 2017:10:25:18:06:53:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = lut 130 reg 129 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  addfix8_add_sub
	( 
	clock,
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   clock;
	input   [63:0]  dataa;
	input   [63:0]  datab;
	output   [63:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   clock;
	tri0   [63:0]  dataa;
	tri0   [63:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[63:0]	add_sub_cell_ffa;
	reg	[0:0]	inter_regrs_cin_ffa0;
	reg	[63:0]	pad_cell_ffa;
	wire  [0:0]   wire_add_sub_cella_0cout;
	wire  [0:0]   wire_add_sub_cella_1cout;
	wire  [0:0]   wire_add_sub_cella_2cout;
	wire  [0:0]   wire_add_sub_cella_3cout;
	wire  [0:0]   wire_add_sub_cella_4cout;
	wire  [0:0]   wire_add_sub_cella_5cout;
	wire  [0:0]   wire_add_sub_cella_6cout;
	wire  [0:0]   wire_add_sub_cella_7cout;
	wire  [0:0]   wire_add_sub_cella_8cout;
	wire  [0:0]   wire_add_sub_cella_9cout;
	wire  [0:0]   wire_add_sub_cella_10cout;
	wire  [0:0]   wire_add_sub_cella_11cout;
	wire  [0:0]   wire_add_sub_cella_12cout;
	wire  [0:0]   wire_add_sub_cella_13cout;
	wire  [0:0]   wire_add_sub_cella_14cout;
	wire  [0:0]   wire_add_sub_cella_15cout;
	wire  [0:0]   wire_add_sub_cella_16cout;
	wire  [0:0]   wire_add_sub_cella_17cout;
	wire  [0:0]   wire_add_sub_cella_18cout;
	wire  [0:0]   wire_add_sub_cella_19cout;
	wire  [0:0]   wire_add_sub_cella_20cout;
	wire  [0:0]   wire_add_sub_cella_21cout;
	wire  [0:0]   wire_add_sub_cella_22cout;
	wire  [0:0]   wire_add_sub_cella_23cout;
	wire  [0:0]   wire_add_sub_cella_24cout;
	wire  [0:0]   wire_add_sub_cella_25cout;
	wire  [0:0]   wire_add_sub_cella_26cout;
	wire  [0:0]   wire_add_sub_cella_27cout;
	wire  [0:0]   wire_add_sub_cella_28cout;
	wire  [0:0]   wire_add_sub_cella_29cout;
	wire  [0:0]   wire_add_sub_cella_30cout;
	wire  [0:0]   wire_add_sub_cella_31cout;
	wire  [0:0]   wire_add_sub_cella_32cout;
	wire  [0:0]   wire_add_sub_cella_33cout;
	wire  [0:0]   wire_add_sub_cella_34cout;
	wire  [0:0]   wire_add_sub_cella_35cout;
	wire  [0:0]   wire_add_sub_cella_36cout;
	wire  [0:0]   wire_add_sub_cella_37cout;
	wire  [0:0]   wire_add_sub_cella_38cout;
	wire  [0:0]   wire_add_sub_cella_39cout;
	wire  [0:0]   wire_add_sub_cella_40cout;
	wire  [0:0]   wire_add_sub_cella_41cout;
	wire  [0:0]   wire_add_sub_cella_42cout;
	wire  [0:0]   wire_add_sub_cella_43cout;
	wire  [0:0]   wire_add_sub_cella_44cout;
	wire  [0:0]   wire_add_sub_cella_45cout;
	wire  [0:0]   wire_add_sub_cella_46cout;
	wire  [0:0]   wire_add_sub_cella_47cout;
	wire  [0:0]   wire_add_sub_cella_48cout;
	wire  [0:0]   wire_add_sub_cella_49cout;
	wire  [0:0]   wire_add_sub_cella_50cout;
	wire  [0:0]   wire_add_sub_cella_51cout;
	wire  [0:0]   wire_add_sub_cella_52cout;
	wire  [0:0]   wire_add_sub_cella_53cout;
	wire  [0:0]   wire_add_sub_cella_54cout;
	wire  [0:0]   wire_add_sub_cella_55cout;
	wire  [0:0]   wire_add_sub_cella_56cout;
	wire  [0:0]   wire_add_sub_cella_57cout;
	wire  [0:0]   wire_add_sub_cella_58cout;
	wire  [0:0]   wire_add_sub_cella_59cout;
	wire  [0:0]   wire_add_sub_cella_60cout;
	wire  [0:0]   wire_add_sub_cella_61cout;
	wire  [0:0]   wire_add_sub_cella_62cout;
	wire  [63:0]   wire_add_sub_cella_datad;
	wire  [63:0]   wire_add_sub_cella_dataf;
	wire  [63:0]   wire_add_sub_cella_sumout;
	wire  [0:0]   wire_inter_regrs_cina_sumout;
	wire  [0:0]   wire_inter_regrs_couta_0cout;
	wire  [0:0]   wire_pad_cella_0cout;
	wire  [0:0]   wire_pad_cella_1cout;
	wire  [0:0]   wire_pad_cella_2cout;
	wire  [0:0]   wire_pad_cella_3cout;
	wire  [0:0]   wire_pad_cella_4cout;
	wire  [0:0]   wire_pad_cella_5cout;
	wire  [0:0]   wire_pad_cella_6cout;
	wire  [0:0]   wire_pad_cella_7cout;
	wire  [0:0]   wire_pad_cella_8cout;
	wire  [0:0]   wire_pad_cella_9cout;
	wire  [0:0]   wire_pad_cella_10cout;
	wire  [0:0]   wire_pad_cella_11cout;
	wire  [0:0]   wire_pad_cella_12cout;
	wire  [0:0]   wire_pad_cella_13cout;
	wire  [0:0]   wire_pad_cella_14cout;
	wire  [0:0]   wire_pad_cella_15cout;
	wire  [0:0]   wire_pad_cella_16cout;
	wire  [0:0]   wire_pad_cella_17cout;
	wire  [0:0]   wire_pad_cella_18cout;
	wire  [0:0]   wire_pad_cella_19cout;
	wire  [0:0]   wire_pad_cella_20cout;
	wire  [0:0]   wire_pad_cella_21cout;
	wire  [0:0]   wire_pad_cella_22cout;
	wire  [0:0]   wire_pad_cella_23cout;
	wire  [0:0]   wire_pad_cella_24cout;
	wire  [0:0]   wire_pad_cella_25cout;
	wire  [0:0]   wire_pad_cella_26cout;
	wire  [0:0]   wire_pad_cella_27cout;
	wire  [0:0]   wire_pad_cella_28cout;
	wire  [0:0]   wire_pad_cella_29cout;
	wire  [0:0]   wire_pad_cella_30cout;
	wire  [0:0]   wire_pad_cella_32cout;
	wire  [0:0]   wire_pad_cella_33cout;
	wire  [0:0]   wire_pad_cella_34cout;
	wire  [0:0]   wire_pad_cella_35cout;
	wire  [0:0]   wire_pad_cella_36cout;
	wire  [0:0]   wire_pad_cella_37cout;
	wire  [0:0]   wire_pad_cella_38cout;
	wire  [0:0]   wire_pad_cella_39cout;
	wire  [0:0]   wire_pad_cella_40cout;
	wire  [0:0]   wire_pad_cella_41cout;
	wire  [0:0]   wire_pad_cella_42cout;
	wire  [0:0]   wire_pad_cella_43cout;
	wire  [0:0]   wire_pad_cella_44cout;
	wire  [0:0]   wire_pad_cella_45cout;
	wire  [0:0]   wire_pad_cella_46cout;
	wire  [0:0]   wire_pad_cella_47cout;
	wire  [0:0]   wire_pad_cella_48cout;
	wire  [0:0]   wire_pad_cella_49cout;
	wire  [0:0]   wire_pad_cella_50cout;
	wire  [0:0]   wire_pad_cella_51cout;
	wire  [0:0]   wire_pad_cella_52cout;
	wire  [0:0]   wire_pad_cella_53cout;
	wire  [0:0]   wire_pad_cella_54cout;
	wire  [0:0]   wire_pad_cella_55cout;
	wire  [0:0]   wire_pad_cella_56cout;
	wire  [0:0]   wire_pad_cella_57cout;
	wire  [0:0]   wire_pad_cella_58cout;
	wire  [0:0]   wire_pad_cella_59cout;
	wire  [0:0]   wire_pad_cella_60cout;
	wire  [0:0]   wire_pad_cella_61cout;
	wire  [0:0]   wire_pad_cella_62cout;
	wire  [63:0]   wire_pad_cella_datad;
	wire  [63:0]   wire_pad_cella_sumout;

	// synopsys translate_off
	initial
		add_sub_cell_ffa = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		  add_sub_cell_ffa <= wire_add_sub_cella_sumout;
	// synopsys translate_off
	initial
		inter_regrs_cin_ffa0 = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		  inter_regrs_cin_ffa0 <= wire_inter_regrs_cina_sumout[0:0];
	// synopsys translate_off
	initial
		pad_cell_ffa = 0;
	// synopsys translate_on
	always @ ( posedge clock)
		  pad_cell_ffa <= wire_pad_cella_sumout;
	stratixv_lcell_comb   add_sub_cella_0
	( 
	.cin(1'b0),
	.combout(),
	.cout(wire_add_sub_cella_0cout[0:0]),
	.datad(wire_add_sub_cella_datad[0:0]),
	.dataf(wire_add_sub_cella_dataf[0:0]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_0.extended_lut = "off",
		add_sub_cella_0.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_0.shared_arith = "off",
		add_sub_cella_0.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_1
	( 
	.cin(wire_add_sub_cella_0cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_1cout[0:0]),
	.datad(wire_add_sub_cella_datad[1:1]),
	.dataf(wire_add_sub_cella_dataf[1:1]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[1:1]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_1.extended_lut = "off",
		add_sub_cella_1.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_1.shared_arith = "off",
		add_sub_cella_1.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_2
	( 
	.cin(wire_add_sub_cella_1cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_2cout[0:0]),
	.datad(wire_add_sub_cella_datad[2:2]),
	.dataf(wire_add_sub_cella_dataf[2:2]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[2:2]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_2.extended_lut = "off",
		add_sub_cella_2.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_2.shared_arith = "off",
		add_sub_cella_2.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_3
	( 
	.cin(wire_add_sub_cella_2cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_3cout[0:0]),
	.datad(wire_add_sub_cella_datad[3:3]),
	.dataf(wire_add_sub_cella_dataf[3:3]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[3:3]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_3.extended_lut = "off",
		add_sub_cella_3.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_3.shared_arith = "off",
		add_sub_cella_3.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_4
	( 
	.cin(wire_add_sub_cella_3cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_4cout[0:0]),
	.datad(wire_add_sub_cella_datad[4:4]),
	.dataf(wire_add_sub_cella_dataf[4:4]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[4:4]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_4.extended_lut = "off",
		add_sub_cella_4.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_4.shared_arith = "off",
		add_sub_cella_4.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_5
	( 
	.cin(wire_add_sub_cella_4cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_5cout[0:0]),
	.datad(wire_add_sub_cella_datad[5:5]),
	.dataf(wire_add_sub_cella_dataf[5:5]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[5:5]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_5.extended_lut = "off",
		add_sub_cella_5.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_5.shared_arith = "off",
		add_sub_cella_5.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_6
	( 
	.cin(wire_add_sub_cella_5cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_6cout[0:0]),
	.datad(wire_add_sub_cella_datad[6:6]),
	.dataf(wire_add_sub_cella_dataf[6:6]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[6:6]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_6.extended_lut = "off",
		add_sub_cella_6.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_6.shared_arith = "off",
		add_sub_cella_6.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_7
	( 
	.cin(wire_add_sub_cella_6cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_7cout[0:0]),
	.datad(wire_add_sub_cella_datad[7:7]),
	.dataf(wire_add_sub_cella_dataf[7:7]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[7:7]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_7.extended_lut = "off",
		add_sub_cella_7.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_7.shared_arith = "off",
		add_sub_cella_7.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_8
	( 
	.cin(wire_add_sub_cella_7cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_8cout[0:0]),
	.datad(wire_add_sub_cella_datad[8:8]),
	.dataf(wire_add_sub_cella_dataf[8:8]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[8:8]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_8.extended_lut = "off",
		add_sub_cella_8.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_8.shared_arith = "off",
		add_sub_cella_8.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_9
	( 
	.cin(wire_add_sub_cella_8cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_9cout[0:0]),
	.datad(wire_add_sub_cella_datad[9:9]),
	.dataf(wire_add_sub_cella_dataf[9:9]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[9:9]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_9.extended_lut = "off",
		add_sub_cella_9.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_9.shared_arith = "off",
		add_sub_cella_9.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_10
	( 
	.cin(wire_add_sub_cella_9cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_10cout[0:0]),
	.datad(wire_add_sub_cella_datad[10:10]),
	.dataf(wire_add_sub_cella_dataf[10:10]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[10:10]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_10.extended_lut = "off",
		add_sub_cella_10.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_10.shared_arith = "off",
		add_sub_cella_10.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_11
	( 
	.cin(wire_add_sub_cella_10cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_11cout[0:0]),
	.datad(wire_add_sub_cella_datad[11:11]),
	.dataf(wire_add_sub_cella_dataf[11:11]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[11:11]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_11.extended_lut = "off",
		add_sub_cella_11.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_11.shared_arith = "off",
		add_sub_cella_11.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_12
	( 
	.cin(wire_add_sub_cella_11cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_12cout[0:0]),
	.datad(wire_add_sub_cella_datad[12:12]),
	.dataf(wire_add_sub_cella_dataf[12:12]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[12:12]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_12.extended_lut = "off",
		add_sub_cella_12.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_12.shared_arith = "off",
		add_sub_cella_12.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_13
	( 
	.cin(wire_add_sub_cella_12cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_13cout[0:0]),
	.datad(wire_add_sub_cella_datad[13:13]),
	.dataf(wire_add_sub_cella_dataf[13:13]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[13:13]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_13.extended_lut = "off",
		add_sub_cella_13.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_13.shared_arith = "off",
		add_sub_cella_13.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_14
	( 
	.cin(wire_add_sub_cella_13cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_14cout[0:0]),
	.datad(wire_add_sub_cella_datad[14:14]),
	.dataf(wire_add_sub_cella_dataf[14:14]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[14:14]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_14.extended_lut = "off",
		add_sub_cella_14.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_14.shared_arith = "off",
		add_sub_cella_14.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_15
	( 
	.cin(wire_add_sub_cella_14cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_15cout[0:0]),
	.datad(wire_add_sub_cella_datad[15:15]),
	.dataf(wire_add_sub_cella_dataf[15:15]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[15:15]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_15.extended_lut = "off",
		add_sub_cella_15.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_15.shared_arith = "off",
		add_sub_cella_15.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_16
	( 
	.cin(wire_add_sub_cella_15cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_16cout[0:0]),
	.datad(wire_add_sub_cella_datad[16:16]),
	.dataf(wire_add_sub_cella_dataf[16:16]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[16:16]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_16.extended_lut = "off",
		add_sub_cella_16.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_16.shared_arith = "off",
		add_sub_cella_16.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_17
	( 
	.cin(wire_add_sub_cella_16cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_17cout[0:0]),
	.datad(wire_add_sub_cella_datad[17:17]),
	.dataf(wire_add_sub_cella_dataf[17:17]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[17:17]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_17.extended_lut = "off",
		add_sub_cella_17.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_17.shared_arith = "off",
		add_sub_cella_17.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_18
	( 
	.cin(wire_add_sub_cella_17cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_18cout[0:0]),
	.datad(wire_add_sub_cella_datad[18:18]),
	.dataf(wire_add_sub_cella_dataf[18:18]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[18:18]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_18.extended_lut = "off",
		add_sub_cella_18.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_18.shared_arith = "off",
		add_sub_cella_18.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_19
	( 
	.cin(wire_add_sub_cella_18cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_19cout[0:0]),
	.datad(wire_add_sub_cella_datad[19:19]),
	.dataf(wire_add_sub_cella_dataf[19:19]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[19:19]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_19.extended_lut = "off",
		add_sub_cella_19.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_19.shared_arith = "off",
		add_sub_cella_19.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_20
	( 
	.cin(wire_add_sub_cella_19cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_20cout[0:0]),
	.datad(wire_add_sub_cella_datad[20:20]),
	.dataf(wire_add_sub_cella_dataf[20:20]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[20:20]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_20.extended_lut = "off",
		add_sub_cella_20.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_20.shared_arith = "off",
		add_sub_cella_20.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_21
	( 
	.cin(wire_add_sub_cella_20cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_21cout[0:0]),
	.datad(wire_add_sub_cella_datad[21:21]),
	.dataf(wire_add_sub_cella_dataf[21:21]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[21:21]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_21.extended_lut = "off",
		add_sub_cella_21.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_21.shared_arith = "off",
		add_sub_cella_21.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_22
	( 
	.cin(wire_add_sub_cella_21cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_22cout[0:0]),
	.datad(wire_add_sub_cella_datad[22:22]),
	.dataf(wire_add_sub_cella_dataf[22:22]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[22:22]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_22.extended_lut = "off",
		add_sub_cella_22.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_22.shared_arith = "off",
		add_sub_cella_22.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_23
	( 
	.cin(wire_add_sub_cella_22cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_23cout[0:0]),
	.datad(wire_add_sub_cella_datad[23:23]),
	.dataf(wire_add_sub_cella_dataf[23:23]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[23:23]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_23.extended_lut = "off",
		add_sub_cella_23.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_23.shared_arith = "off",
		add_sub_cella_23.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_24
	( 
	.cin(wire_add_sub_cella_23cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_24cout[0:0]),
	.datad(wire_add_sub_cella_datad[24:24]),
	.dataf(wire_add_sub_cella_dataf[24:24]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[24:24]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_24.extended_lut = "off",
		add_sub_cella_24.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_24.shared_arith = "off",
		add_sub_cella_24.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_25
	( 
	.cin(wire_add_sub_cella_24cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_25cout[0:0]),
	.datad(wire_add_sub_cella_datad[25:25]),
	.dataf(wire_add_sub_cella_dataf[25:25]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[25:25]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_25.extended_lut = "off",
		add_sub_cella_25.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_25.shared_arith = "off",
		add_sub_cella_25.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_26
	( 
	.cin(wire_add_sub_cella_25cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_26cout[0:0]),
	.datad(wire_add_sub_cella_datad[26:26]),
	.dataf(wire_add_sub_cella_dataf[26:26]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[26:26]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_26.extended_lut = "off",
		add_sub_cella_26.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_26.shared_arith = "off",
		add_sub_cella_26.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_27
	( 
	.cin(wire_add_sub_cella_26cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_27cout[0:0]),
	.datad(wire_add_sub_cella_datad[27:27]),
	.dataf(wire_add_sub_cella_dataf[27:27]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[27:27]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_27.extended_lut = "off",
		add_sub_cella_27.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_27.shared_arith = "off",
		add_sub_cella_27.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_28
	( 
	.cin(wire_add_sub_cella_27cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_28cout[0:0]),
	.datad(wire_add_sub_cella_datad[28:28]),
	.dataf(wire_add_sub_cella_dataf[28:28]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[28:28]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_28.extended_lut = "off",
		add_sub_cella_28.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_28.shared_arith = "off",
		add_sub_cella_28.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_29
	( 
	.cin(wire_add_sub_cella_28cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_29cout[0:0]),
	.datad(wire_add_sub_cella_datad[29:29]),
	.dataf(wire_add_sub_cella_dataf[29:29]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[29:29]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_29.extended_lut = "off",
		add_sub_cella_29.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_29.shared_arith = "off",
		add_sub_cella_29.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_30
	( 
	.cin(wire_add_sub_cella_29cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_30cout[0:0]),
	.datad(wire_add_sub_cella_datad[30:30]),
	.dataf(wire_add_sub_cella_dataf[30:30]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[30:30]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_30.extended_lut = "off",
		add_sub_cella_30.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_30.shared_arith = "off",
		add_sub_cella_30.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_31
	( 
	.cin(wire_add_sub_cella_30cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_31cout[0:0]),
	.datad(wire_add_sub_cella_datad[31:31]),
	.dataf(wire_add_sub_cella_dataf[31:31]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[31:31]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_31.extended_lut = "off",
		add_sub_cella_31.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_31.shared_arith = "off",
		add_sub_cella_31.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_32
	( 
	.cin(1'b0),
	.combout(),
	.cout(wire_add_sub_cella_32cout[0:0]),
	.datad(wire_add_sub_cella_datad[32:32]),
	.dataf(wire_add_sub_cella_dataf[32:32]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[32:32]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_32.extended_lut = "off",
		add_sub_cella_32.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_32.shared_arith = "off",
		add_sub_cella_32.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_33
	( 
	.cin(wire_add_sub_cella_32cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_33cout[0:0]),
	.datad(wire_add_sub_cella_datad[33:33]),
	.dataf(wire_add_sub_cella_dataf[33:33]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[33:33]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_33.extended_lut = "off",
		add_sub_cella_33.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_33.shared_arith = "off",
		add_sub_cella_33.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_34
	( 
	.cin(wire_add_sub_cella_33cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_34cout[0:0]),
	.datad(wire_add_sub_cella_datad[34:34]),
	.dataf(wire_add_sub_cella_dataf[34:34]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[34:34]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_34.extended_lut = "off",
		add_sub_cella_34.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_34.shared_arith = "off",
		add_sub_cella_34.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_35
	( 
	.cin(wire_add_sub_cella_34cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_35cout[0:0]),
	.datad(wire_add_sub_cella_datad[35:35]),
	.dataf(wire_add_sub_cella_dataf[35:35]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[35:35]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_35.extended_lut = "off",
		add_sub_cella_35.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_35.shared_arith = "off",
		add_sub_cella_35.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_36
	( 
	.cin(wire_add_sub_cella_35cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_36cout[0:0]),
	.datad(wire_add_sub_cella_datad[36:36]),
	.dataf(wire_add_sub_cella_dataf[36:36]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[36:36]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_36.extended_lut = "off",
		add_sub_cella_36.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_36.shared_arith = "off",
		add_sub_cella_36.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_37
	( 
	.cin(wire_add_sub_cella_36cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_37cout[0:0]),
	.datad(wire_add_sub_cella_datad[37:37]),
	.dataf(wire_add_sub_cella_dataf[37:37]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[37:37]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_37.extended_lut = "off",
		add_sub_cella_37.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_37.shared_arith = "off",
		add_sub_cella_37.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_38
	( 
	.cin(wire_add_sub_cella_37cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_38cout[0:0]),
	.datad(wire_add_sub_cella_datad[38:38]),
	.dataf(wire_add_sub_cella_dataf[38:38]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[38:38]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_38.extended_lut = "off",
		add_sub_cella_38.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_38.shared_arith = "off",
		add_sub_cella_38.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_39
	( 
	.cin(wire_add_sub_cella_38cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_39cout[0:0]),
	.datad(wire_add_sub_cella_datad[39:39]),
	.dataf(wire_add_sub_cella_dataf[39:39]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[39:39]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_39.extended_lut = "off",
		add_sub_cella_39.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_39.shared_arith = "off",
		add_sub_cella_39.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_40
	( 
	.cin(wire_add_sub_cella_39cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_40cout[0:0]),
	.datad(wire_add_sub_cella_datad[40:40]),
	.dataf(wire_add_sub_cella_dataf[40:40]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[40:40]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_40.extended_lut = "off",
		add_sub_cella_40.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_40.shared_arith = "off",
		add_sub_cella_40.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_41
	( 
	.cin(wire_add_sub_cella_40cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_41cout[0:0]),
	.datad(wire_add_sub_cella_datad[41:41]),
	.dataf(wire_add_sub_cella_dataf[41:41]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[41:41]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_41.extended_lut = "off",
		add_sub_cella_41.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_41.shared_arith = "off",
		add_sub_cella_41.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_42
	( 
	.cin(wire_add_sub_cella_41cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_42cout[0:0]),
	.datad(wire_add_sub_cella_datad[42:42]),
	.dataf(wire_add_sub_cella_dataf[42:42]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[42:42]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_42.extended_lut = "off",
		add_sub_cella_42.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_42.shared_arith = "off",
		add_sub_cella_42.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_43
	( 
	.cin(wire_add_sub_cella_42cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_43cout[0:0]),
	.datad(wire_add_sub_cella_datad[43:43]),
	.dataf(wire_add_sub_cella_dataf[43:43]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[43:43]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_43.extended_lut = "off",
		add_sub_cella_43.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_43.shared_arith = "off",
		add_sub_cella_43.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_44
	( 
	.cin(wire_add_sub_cella_43cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_44cout[0:0]),
	.datad(wire_add_sub_cella_datad[44:44]),
	.dataf(wire_add_sub_cella_dataf[44:44]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[44:44]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_44.extended_lut = "off",
		add_sub_cella_44.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_44.shared_arith = "off",
		add_sub_cella_44.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_45
	( 
	.cin(wire_add_sub_cella_44cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_45cout[0:0]),
	.datad(wire_add_sub_cella_datad[45:45]),
	.dataf(wire_add_sub_cella_dataf[45:45]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[45:45]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_45.extended_lut = "off",
		add_sub_cella_45.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_45.shared_arith = "off",
		add_sub_cella_45.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_46
	( 
	.cin(wire_add_sub_cella_45cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_46cout[0:0]),
	.datad(wire_add_sub_cella_datad[46:46]),
	.dataf(wire_add_sub_cella_dataf[46:46]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[46:46]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_46.extended_lut = "off",
		add_sub_cella_46.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_46.shared_arith = "off",
		add_sub_cella_46.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_47
	( 
	.cin(wire_add_sub_cella_46cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_47cout[0:0]),
	.datad(wire_add_sub_cella_datad[47:47]),
	.dataf(wire_add_sub_cella_dataf[47:47]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[47:47]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_47.extended_lut = "off",
		add_sub_cella_47.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_47.shared_arith = "off",
		add_sub_cella_47.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_48
	( 
	.cin(wire_add_sub_cella_47cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_48cout[0:0]),
	.datad(wire_add_sub_cella_datad[48:48]),
	.dataf(wire_add_sub_cella_dataf[48:48]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[48:48]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_48.extended_lut = "off",
		add_sub_cella_48.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_48.shared_arith = "off",
		add_sub_cella_48.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_49
	( 
	.cin(wire_add_sub_cella_48cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_49cout[0:0]),
	.datad(wire_add_sub_cella_datad[49:49]),
	.dataf(wire_add_sub_cella_dataf[49:49]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[49:49]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_49.extended_lut = "off",
		add_sub_cella_49.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_49.shared_arith = "off",
		add_sub_cella_49.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_50
	( 
	.cin(wire_add_sub_cella_49cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_50cout[0:0]),
	.datad(wire_add_sub_cella_datad[50:50]),
	.dataf(wire_add_sub_cella_dataf[50:50]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[50:50]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_50.extended_lut = "off",
		add_sub_cella_50.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_50.shared_arith = "off",
		add_sub_cella_50.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_51
	( 
	.cin(wire_add_sub_cella_50cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_51cout[0:0]),
	.datad(wire_add_sub_cella_datad[51:51]),
	.dataf(wire_add_sub_cella_dataf[51:51]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[51:51]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_51.extended_lut = "off",
		add_sub_cella_51.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_51.shared_arith = "off",
		add_sub_cella_51.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_52
	( 
	.cin(wire_add_sub_cella_51cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_52cout[0:0]),
	.datad(wire_add_sub_cella_datad[52:52]),
	.dataf(wire_add_sub_cella_dataf[52:52]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[52:52]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_52.extended_lut = "off",
		add_sub_cella_52.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_52.shared_arith = "off",
		add_sub_cella_52.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_53
	( 
	.cin(wire_add_sub_cella_52cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_53cout[0:0]),
	.datad(wire_add_sub_cella_datad[53:53]),
	.dataf(wire_add_sub_cella_dataf[53:53]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[53:53]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_53.extended_lut = "off",
		add_sub_cella_53.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_53.shared_arith = "off",
		add_sub_cella_53.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_54
	( 
	.cin(wire_add_sub_cella_53cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_54cout[0:0]),
	.datad(wire_add_sub_cella_datad[54:54]),
	.dataf(wire_add_sub_cella_dataf[54:54]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[54:54]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_54.extended_lut = "off",
		add_sub_cella_54.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_54.shared_arith = "off",
		add_sub_cella_54.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_55
	( 
	.cin(wire_add_sub_cella_54cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_55cout[0:0]),
	.datad(wire_add_sub_cella_datad[55:55]),
	.dataf(wire_add_sub_cella_dataf[55:55]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[55:55]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_55.extended_lut = "off",
		add_sub_cella_55.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_55.shared_arith = "off",
		add_sub_cella_55.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_56
	( 
	.cin(wire_add_sub_cella_55cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_56cout[0:0]),
	.datad(wire_add_sub_cella_datad[56:56]),
	.dataf(wire_add_sub_cella_dataf[56:56]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[56:56]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_56.extended_lut = "off",
		add_sub_cella_56.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_56.shared_arith = "off",
		add_sub_cella_56.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_57
	( 
	.cin(wire_add_sub_cella_56cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_57cout[0:0]),
	.datad(wire_add_sub_cella_datad[57:57]),
	.dataf(wire_add_sub_cella_dataf[57:57]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[57:57]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_57.extended_lut = "off",
		add_sub_cella_57.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_57.shared_arith = "off",
		add_sub_cella_57.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_58
	( 
	.cin(wire_add_sub_cella_57cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_58cout[0:0]),
	.datad(wire_add_sub_cella_datad[58:58]),
	.dataf(wire_add_sub_cella_dataf[58:58]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[58:58]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_58.extended_lut = "off",
		add_sub_cella_58.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_58.shared_arith = "off",
		add_sub_cella_58.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_59
	( 
	.cin(wire_add_sub_cella_58cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_59cout[0:0]),
	.datad(wire_add_sub_cella_datad[59:59]),
	.dataf(wire_add_sub_cella_dataf[59:59]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[59:59]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_59.extended_lut = "off",
		add_sub_cella_59.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_59.shared_arith = "off",
		add_sub_cella_59.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_60
	( 
	.cin(wire_add_sub_cella_59cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_60cout[0:0]),
	.datad(wire_add_sub_cella_datad[60:60]),
	.dataf(wire_add_sub_cella_dataf[60:60]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[60:60]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_60.extended_lut = "off",
		add_sub_cella_60.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_60.shared_arith = "off",
		add_sub_cella_60.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_61
	( 
	.cin(wire_add_sub_cella_60cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_61cout[0:0]),
	.datad(wire_add_sub_cella_datad[61:61]),
	.dataf(wire_add_sub_cella_dataf[61:61]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[61:61]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_61.extended_lut = "off",
		add_sub_cella_61.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_61.shared_arith = "off",
		add_sub_cella_61.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_62
	( 
	.cin(wire_add_sub_cella_61cout[0:0]),
	.combout(),
	.cout(wire_add_sub_cella_62cout[0:0]),
	.datad(wire_add_sub_cella_datad[62:62]),
	.dataf(wire_add_sub_cella_dataf[62:62]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[62:62]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_62.extended_lut = "off",
		add_sub_cella_62.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_62.shared_arith = "off",
		add_sub_cella_62.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   add_sub_cella_63
	( 
	.cin(wire_add_sub_cella_62cout[0:0]),
	.combout(),
	.cout(),
	.datad(wire_add_sub_cella_datad[63:63]),
	.dataf(wire_add_sub_cella_dataf[63:63]),
	.shareout(),
	.sumout(wire_add_sub_cella_sumout[63:63]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		add_sub_cella_63.extended_lut = "off",
		add_sub_cella_63.lut_mask = 64'h000000FF0000FF00,
		add_sub_cella_63.shared_arith = "off",
		add_sub_cella_63.lpm_type = "stratixv_lcell_comb";
	assign
		wire_add_sub_cella_datad = dataa,
		wire_add_sub_cella_dataf = datab;
	stratixv_lcell_comb   inter_regrs_cina_0
	( 
	.cin(wire_add_sub_cella_31cout[0:0]),
	.combout(),
	.cout(),
	.dataa(1'b1),
	.shareout(),
	.sumout(wire_inter_regrs_cina_sumout[0:0]),
	.datab(1'b0),
	.datac(1'b0),
	.datad(1'b0),
	.datae(1'b0),
	.dataf(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		inter_regrs_cina_0.extended_lut = "off",
		inter_regrs_cina_0.lut_mask = 64'h0000AAAA00005555,
		inter_regrs_cina_0.shared_arith = "off",
		inter_regrs_cina_0.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   inter_regrs_couta_0
	( 
	.cin(1'b0),
	.combout(),
	.cout(wire_inter_regrs_couta_0cout[0:0]),
	.dataa(inter_regrs_cin_ffa0),
	.shareout(),
	.sumout(),
	.datab(1'b0),
	.datac(1'b0),
	.datad(1'b0),
	.datae(1'b0),
	.dataf(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		inter_regrs_couta_0.extended_lut = "off",
		inter_regrs_couta_0.lut_mask = 64'h000055550000AAAA,
		inter_regrs_couta_0.shared_arith = "off",
		inter_regrs_couta_0.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_0
	( 
	.cin(1'b0),
	.combout(),
	.cout(wire_pad_cella_0cout[0:0]),
	.datad(wire_pad_cella_datad[0:0]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[0:0]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_0.extended_lut = "off",
		pad_cella_0.lut_mask = 64'h000000FF0000FF00,
		pad_cella_0.shared_arith = "off",
		pad_cella_0.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_1
	( 
	.cin(wire_pad_cella_0cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_1cout[0:0]),
	.datad(wire_pad_cella_datad[1:1]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[1:1]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_1.extended_lut = "off",
		pad_cella_1.lut_mask = 64'h000000FF0000FF00,
		pad_cella_1.shared_arith = "off",
		pad_cella_1.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_2
	( 
	.cin(wire_pad_cella_1cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_2cout[0:0]),
	.datad(wire_pad_cella_datad[2:2]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[2:2]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_2.extended_lut = "off",
		pad_cella_2.lut_mask = 64'h000000FF0000FF00,
		pad_cella_2.shared_arith = "off",
		pad_cella_2.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_3
	( 
	.cin(wire_pad_cella_2cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_3cout[0:0]),
	.datad(wire_pad_cella_datad[3:3]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[3:3]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_3.extended_lut = "off",
		pad_cella_3.lut_mask = 64'h000000FF0000FF00,
		pad_cella_3.shared_arith = "off",
		pad_cella_3.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_4
	( 
	.cin(wire_pad_cella_3cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_4cout[0:0]),
	.datad(wire_pad_cella_datad[4:4]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[4:4]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_4.extended_lut = "off",
		pad_cella_4.lut_mask = 64'h000000FF0000FF00,
		pad_cella_4.shared_arith = "off",
		pad_cella_4.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_5
	( 
	.cin(wire_pad_cella_4cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_5cout[0:0]),
	.datad(wire_pad_cella_datad[5:5]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[5:5]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_5.extended_lut = "off",
		pad_cella_5.lut_mask = 64'h000000FF0000FF00,
		pad_cella_5.shared_arith = "off",
		pad_cella_5.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_6
	( 
	.cin(wire_pad_cella_5cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_6cout[0:0]),
	.datad(wire_pad_cella_datad[6:6]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[6:6]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_6.extended_lut = "off",
		pad_cella_6.lut_mask = 64'h000000FF0000FF00,
		pad_cella_6.shared_arith = "off",
		pad_cella_6.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_7
	( 
	.cin(wire_pad_cella_6cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_7cout[0:0]),
	.datad(wire_pad_cella_datad[7:7]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[7:7]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_7.extended_lut = "off",
		pad_cella_7.lut_mask = 64'h000000FF0000FF00,
		pad_cella_7.shared_arith = "off",
		pad_cella_7.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_8
	( 
	.cin(wire_pad_cella_7cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_8cout[0:0]),
	.datad(wire_pad_cella_datad[8:8]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[8:8]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_8.extended_lut = "off",
		pad_cella_8.lut_mask = 64'h000000FF0000FF00,
		pad_cella_8.shared_arith = "off",
		pad_cella_8.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_9
	( 
	.cin(wire_pad_cella_8cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_9cout[0:0]),
	.datad(wire_pad_cella_datad[9:9]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[9:9]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_9.extended_lut = "off",
		pad_cella_9.lut_mask = 64'h000000FF0000FF00,
		pad_cella_9.shared_arith = "off",
		pad_cella_9.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_10
	( 
	.cin(wire_pad_cella_9cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_10cout[0:0]),
	.datad(wire_pad_cella_datad[10:10]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[10:10]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_10.extended_lut = "off",
		pad_cella_10.lut_mask = 64'h000000FF0000FF00,
		pad_cella_10.shared_arith = "off",
		pad_cella_10.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_11
	( 
	.cin(wire_pad_cella_10cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_11cout[0:0]),
	.datad(wire_pad_cella_datad[11:11]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[11:11]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_11.extended_lut = "off",
		pad_cella_11.lut_mask = 64'h000000FF0000FF00,
		pad_cella_11.shared_arith = "off",
		pad_cella_11.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_12
	( 
	.cin(wire_pad_cella_11cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_12cout[0:0]),
	.datad(wire_pad_cella_datad[12:12]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[12:12]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_12.extended_lut = "off",
		pad_cella_12.lut_mask = 64'h000000FF0000FF00,
		pad_cella_12.shared_arith = "off",
		pad_cella_12.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_13
	( 
	.cin(wire_pad_cella_12cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_13cout[0:0]),
	.datad(wire_pad_cella_datad[13:13]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[13:13]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_13.extended_lut = "off",
		pad_cella_13.lut_mask = 64'h000000FF0000FF00,
		pad_cella_13.shared_arith = "off",
		pad_cella_13.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_14
	( 
	.cin(wire_pad_cella_13cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_14cout[0:0]),
	.datad(wire_pad_cella_datad[14:14]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[14:14]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_14.extended_lut = "off",
		pad_cella_14.lut_mask = 64'h000000FF0000FF00,
		pad_cella_14.shared_arith = "off",
		pad_cella_14.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_15
	( 
	.cin(wire_pad_cella_14cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_15cout[0:0]),
	.datad(wire_pad_cella_datad[15:15]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[15:15]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_15.extended_lut = "off",
		pad_cella_15.lut_mask = 64'h000000FF0000FF00,
		pad_cella_15.shared_arith = "off",
		pad_cella_15.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_16
	( 
	.cin(wire_pad_cella_15cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_16cout[0:0]),
	.datad(wire_pad_cella_datad[16:16]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[16:16]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_16.extended_lut = "off",
		pad_cella_16.lut_mask = 64'h000000FF0000FF00,
		pad_cella_16.shared_arith = "off",
		pad_cella_16.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_17
	( 
	.cin(wire_pad_cella_16cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_17cout[0:0]),
	.datad(wire_pad_cella_datad[17:17]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[17:17]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_17.extended_lut = "off",
		pad_cella_17.lut_mask = 64'h000000FF0000FF00,
		pad_cella_17.shared_arith = "off",
		pad_cella_17.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_18
	( 
	.cin(wire_pad_cella_17cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_18cout[0:0]),
	.datad(wire_pad_cella_datad[18:18]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[18:18]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_18.extended_lut = "off",
		pad_cella_18.lut_mask = 64'h000000FF0000FF00,
		pad_cella_18.shared_arith = "off",
		pad_cella_18.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_19
	( 
	.cin(wire_pad_cella_18cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_19cout[0:0]),
	.datad(wire_pad_cella_datad[19:19]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[19:19]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_19.extended_lut = "off",
		pad_cella_19.lut_mask = 64'h000000FF0000FF00,
		pad_cella_19.shared_arith = "off",
		pad_cella_19.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_20
	( 
	.cin(wire_pad_cella_19cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_20cout[0:0]),
	.datad(wire_pad_cella_datad[20:20]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[20:20]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_20.extended_lut = "off",
		pad_cella_20.lut_mask = 64'h000000FF0000FF00,
		pad_cella_20.shared_arith = "off",
		pad_cella_20.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_21
	( 
	.cin(wire_pad_cella_20cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_21cout[0:0]),
	.datad(wire_pad_cella_datad[21:21]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[21:21]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_21.extended_lut = "off",
		pad_cella_21.lut_mask = 64'h000000FF0000FF00,
		pad_cella_21.shared_arith = "off",
		pad_cella_21.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_22
	( 
	.cin(wire_pad_cella_21cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_22cout[0:0]),
	.datad(wire_pad_cella_datad[22:22]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[22:22]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_22.extended_lut = "off",
		pad_cella_22.lut_mask = 64'h000000FF0000FF00,
		pad_cella_22.shared_arith = "off",
		pad_cella_22.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_23
	( 
	.cin(wire_pad_cella_22cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_23cout[0:0]),
	.datad(wire_pad_cella_datad[23:23]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[23:23]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_23.extended_lut = "off",
		pad_cella_23.lut_mask = 64'h000000FF0000FF00,
		pad_cella_23.shared_arith = "off",
		pad_cella_23.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_24
	( 
	.cin(wire_pad_cella_23cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_24cout[0:0]),
	.datad(wire_pad_cella_datad[24:24]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[24:24]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_24.extended_lut = "off",
		pad_cella_24.lut_mask = 64'h000000FF0000FF00,
		pad_cella_24.shared_arith = "off",
		pad_cella_24.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_25
	( 
	.cin(wire_pad_cella_24cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_25cout[0:0]),
	.datad(wire_pad_cella_datad[25:25]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[25:25]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_25.extended_lut = "off",
		pad_cella_25.lut_mask = 64'h000000FF0000FF00,
		pad_cella_25.shared_arith = "off",
		pad_cella_25.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_26
	( 
	.cin(wire_pad_cella_25cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_26cout[0:0]),
	.datad(wire_pad_cella_datad[26:26]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[26:26]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_26.extended_lut = "off",
		pad_cella_26.lut_mask = 64'h000000FF0000FF00,
		pad_cella_26.shared_arith = "off",
		pad_cella_26.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_27
	( 
	.cin(wire_pad_cella_26cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_27cout[0:0]),
	.datad(wire_pad_cella_datad[27:27]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[27:27]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_27.extended_lut = "off",
		pad_cella_27.lut_mask = 64'h000000FF0000FF00,
		pad_cella_27.shared_arith = "off",
		pad_cella_27.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_28
	( 
	.cin(wire_pad_cella_27cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_28cout[0:0]),
	.datad(wire_pad_cella_datad[28:28]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[28:28]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_28.extended_lut = "off",
		pad_cella_28.lut_mask = 64'h000000FF0000FF00,
		pad_cella_28.shared_arith = "off",
		pad_cella_28.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_29
	( 
	.cin(wire_pad_cella_28cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_29cout[0:0]),
	.datad(wire_pad_cella_datad[29:29]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[29:29]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_29.extended_lut = "off",
		pad_cella_29.lut_mask = 64'h000000FF0000FF00,
		pad_cella_29.shared_arith = "off",
		pad_cella_29.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_30
	( 
	.cin(wire_pad_cella_29cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_30cout[0:0]),
	.datad(wire_pad_cella_datad[30:30]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[30:30]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_30.extended_lut = "off",
		pad_cella_30.lut_mask = 64'h000000FF0000FF00,
		pad_cella_30.shared_arith = "off",
		pad_cella_30.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_31
	( 
	.cin(wire_pad_cella_30cout[0:0]),
	.combout(),
	.cout(),
	.datad(wire_pad_cella_datad[31:31]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[31:31]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_31.extended_lut = "off",
		pad_cella_31.lut_mask = 64'h000000FF0000FF00,
		pad_cella_31.shared_arith = "off",
		pad_cella_31.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_32
	( 
	.cin(wire_inter_regrs_couta_0cout),
	.combout(),
	.cout(wire_pad_cella_32cout[0:0]),
	.datad(wire_pad_cella_datad[32:32]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[32:32]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_32.extended_lut = "off",
		pad_cella_32.lut_mask = 64'h000000FF0000FF00,
		pad_cella_32.shared_arith = "off",
		pad_cella_32.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_33
	( 
	.cin(wire_pad_cella_32cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_33cout[0:0]),
	.datad(wire_pad_cella_datad[33:33]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[33:33]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_33.extended_lut = "off",
		pad_cella_33.lut_mask = 64'h000000FF0000FF00,
		pad_cella_33.shared_arith = "off",
		pad_cella_33.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_34
	( 
	.cin(wire_pad_cella_33cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_34cout[0:0]),
	.datad(wire_pad_cella_datad[34:34]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[34:34]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_34.extended_lut = "off",
		pad_cella_34.lut_mask = 64'h000000FF0000FF00,
		pad_cella_34.shared_arith = "off",
		pad_cella_34.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_35
	( 
	.cin(wire_pad_cella_34cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_35cout[0:0]),
	.datad(wire_pad_cella_datad[35:35]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[35:35]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_35.extended_lut = "off",
		pad_cella_35.lut_mask = 64'h000000FF0000FF00,
		pad_cella_35.shared_arith = "off",
		pad_cella_35.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_36
	( 
	.cin(wire_pad_cella_35cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_36cout[0:0]),
	.datad(wire_pad_cella_datad[36:36]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[36:36]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_36.extended_lut = "off",
		pad_cella_36.lut_mask = 64'h000000FF0000FF00,
		pad_cella_36.shared_arith = "off",
		pad_cella_36.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_37
	( 
	.cin(wire_pad_cella_36cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_37cout[0:0]),
	.datad(wire_pad_cella_datad[37:37]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[37:37]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_37.extended_lut = "off",
		pad_cella_37.lut_mask = 64'h000000FF0000FF00,
		pad_cella_37.shared_arith = "off",
		pad_cella_37.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_38
	( 
	.cin(wire_pad_cella_37cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_38cout[0:0]),
	.datad(wire_pad_cella_datad[38:38]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[38:38]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_38.extended_lut = "off",
		pad_cella_38.lut_mask = 64'h000000FF0000FF00,
		pad_cella_38.shared_arith = "off",
		pad_cella_38.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_39
	( 
	.cin(wire_pad_cella_38cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_39cout[0:0]),
	.datad(wire_pad_cella_datad[39:39]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[39:39]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_39.extended_lut = "off",
		pad_cella_39.lut_mask = 64'h000000FF0000FF00,
		pad_cella_39.shared_arith = "off",
		pad_cella_39.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_40
	( 
	.cin(wire_pad_cella_39cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_40cout[0:0]),
	.datad(wire_pad_cella_datad[40:40]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[40:40]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_40.extended_lut = "off",
		pad_cella_40.lut_mask = 64'h000000FF0000FF00,
		pad_cella_40.shared_arith = "off",
		pad_cella_40.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_41
	( 
	.cin(wire_pad_cella_40cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_41cout[0:0]),
	.datad(wire_pad_cella_datad[41:41]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[41:41]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_41.extended_lut = "off",
		pad_cella_41.lut_mask = 64'h000000FF0000FF00,
		pad_cella_41.shared_arith = "off",
		pad_cella_41.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_42
	( 
	.cin(wire_pad_cella_41cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_42cout[0:0]),
	.datad(wire_pad_cella_datad[42:42]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[42:42]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_42.extended_lut = "off",
		pad_cella_42.lut_mask = 64'h000000FF0000FF00,
		pad_cella_42.shared_arith = "off",
		pad_cella_42.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_43
	( 
	.cin(wire_pad_cella_42cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_43cout[0:0]),
	.datad(wire_pad_cella_datad[43:43]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[43:43]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_43.extended_lut = "off",
		pad_cella_43.lut_mask = 64'h000000FF0000FF00,
		pad_cella_43.shared_arith = "off",
		pad_cella_43.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_44
	( 
	.cin(wire_pad_cella_43cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_44cout[0:0]),
	.datad(wire_pad_cella_datad[44:44]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[44:44]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_44.extended_lut = "off",
		pad_cella_44.lut_mask = 64'h000000FF0000FF00,
		pad_cella_44.shared_arith = "off",
		pad_cella_44.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_45
	( 
	.cin(wire_pad_cella_44cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_45cout[0:0]),
	.datad(wire_pad_cella_datad[45:45]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[45:45]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_45.extended_lut = "off",
		pad_cella_45.lut_mask = 64'h000000FF0000FF00,
		pad_cella_45.shared_arith = "off",
		pad_cella_45.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_46
	( 
	.cin(wire_pad_cella_45cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_46cout[0:0]),
	.datad(wire_pad_cella_datad[46:46]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[46:46]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_46.extended_lut = "off",
		pad_cella_46.lut_mask = 64'h000000FF0000FF00,
		pad_cella_46.shared_arith = "off",
		pad_cella_46.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_47
	( 
	.cin(wire_pad_cella_46cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_47cout[0:0]),
	.datad(wire_pad_cella_datad[47:47]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[47:47]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_47.extended_lut = "off",
		pad_cella_47.lut_mask = 64'h000000FF0000FF00,
		pad_cella_47.shared_arith = "off",
		pad_cella_47.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_48
	( 
	.cin(wire_pad_cella_47cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_48cout[0:0]),
	.datad(wire_pad_cella_datad[48:48]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[48:48]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_48.extended_lut = "off",
		pad_cella_48.lut_mask = 64'h000000FF0000FF00,
		pad_cella_48.shared_arith = "off",
		pad_cella_48.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_49
	( 
	.cin(wire_pad_cella_48cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_49cout[0:0]),
	.datad(wire_pad_cella_datad[49:49]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[49:49]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_49.extended_lut = "off",
		pad_cella_49.lut_mask = 64'h000000FF0000FF00,
		pad_cella_49.shared_arith = "off",
		pad_cella_49.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_50
	( 
	.cin(wire_pad_cella_49cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_50cout[0:0]),
	.datad(wire_pad_cella_datad[50:50]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[50:50]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_50.extended_lut = "off",
		pad_cella_50.lut_mask = 64'h000000FF0000FF00,
		pad_cella_50.shared_arith = "off",
		pad_cella_50.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_51
	( 
	.cin(wire_pad_cella_50cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_51cout[0:0]),
	.datad(wire_pad_cella_datad[51:51]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[51:51]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_51.extended_lut = "off",
		pad_cella_51.lut_mask = 64'h000000FF0000FF00,
		pad_cella_51.shared_arith = "off",
		pad_cella_51.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_52
	( 
	.cin(wire_pad_cella_51cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_52cout[0:0]),
	.datad(wire_pad_cella_datad[52:52]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[52:52]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_52.extended_lut = "off",
		pad_cella_52.lut_mask = 64'h000000FF0000FF00,
		pad_cella_52.shared_arith = "off",
		pad_cella_52.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_53
	( 
	.cin(wire_pad_cella_52cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_53cout[0:0]),
	.datad(wire_pad_cella_datad[53:53]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[53:53]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_53.extended_lut = "off",
		pad_cella_53.lut_mask = 64'h000000FF0000FF00,
		pad_cella_53.shared_arith = "off",
		pad_cella_53.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_54
	( 
	.cin(wire_pad_cella_53cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_54cout[0:0]),
	.datad(wire_pad_cella_datad[54:54]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[54:54]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_54.extended_lut = "off",
		pad_cella_54.lut_mask = 64'h000000FF0000FF00,
		pad_cella_54.shared_arith = "off",
		pad_cella_54.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_55
	( 
	.cin(wire_pad_cella_54cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_55cout[0:0]),
	.datad(wire_pad_cella_datad[55:55]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[55:55]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_55.extended_lut = "off",
		pad_cella_55.lut_mask = 64'h000000FF0000FF00,
		pad_cella_55.shared_arith = "off",
		pad_cella_55.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_56
	( 
	.cin(wire_pad_cella_55cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_56cout[0:0]),
	.datad(wire_pad_cella_datad[56:56]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[56:56]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_56.extended_lut = "off",
		pad_cella_56.lut_mask = 64'h000000FF0000FF00,
		pad_cella_56.shared_arith = "off",
		pad_cella_56.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_57
	( 
	.cin(wire_pad_cella_56cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_57cout[0:0]),
	.datad(wire_pad_cella_datad[57:57]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[57:57]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_57.extended_lut = "off",
		pad_cella_57.lut_mask = 64'h000000FF0000FF00,
		pad_cella_57.shared_arith = "off",
		pad_cella_57.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_58
	( 
	.cin(wire_pad_cella_57cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_58cout[0:0]),
	.datad(wire_pad_cella_datad[58:58]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[58:58]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_58.extended_lut = "off",
		pad_cella_58.lut_mask = 64'h000000FF0000FF00,
		pad_cella_58.shared_arith = "off",
		pad_cella_58.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_59
	( 
	.cin(wire_pad_cella_58cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_59cout[0:0]),
	.datad(wire_pad_cella_datad[59:59]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[59:59]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_59.extended_lut = "off",
		pad_cella_59.lut_mask = 64'h000000FF0000FF00,
		pad_cella_59.shared_arith = "off",
		pad_cella_59.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_60
	( 
	.cin(wire_pad_cella_59cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_60cout[0:0]),
	.datad(wire_pad_cella_datad[60:60]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[60:60]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_60.extended_lut = "off",
		pad_cella_60.lut_mask = 64'h000000FF0000FF00,
		pad_cella_60.shared_arith = "off",
		pad_cella_60.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_61
	( 
	.cin(wire_pad_cella_60cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_61cout[0:0]),
	.datad(wire_pad_cella_datad[61:61]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[61:61]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_61.extended_lut = "off",
		pad_cella_61.lut_mask = 64'h000000FF0000FF00,
		pad_cella_61.shared_arith = "off",
		pad_cella_61.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_62
	( 
	.cin(wire_pad_cella_61cout[0:0]),
	.combout(),
	.cout(wire_pad_cella_62cout[0:0]),
	.datad(wire_pad_cella_datad[62:62]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[62:62]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_62.extended_lut = "off",
		pad_cella_62.lut_mask = 64'h000000FF0000FF00,
		pad_cella_62.shared_arith = "off",
		pad_cella_62.lpm_type = "stratixv_lcell_comb";
	stratixv_lcell_comb   pad_cella_63
	( 
	.cin(wire_pad_cella_62cout[0:0]),
	.combout(),
	.cout(),
	.datad(wire_pad_cella_datad[63:63]),
	.dataf(1'b0),
	.shareout(),
	.sumout(wire_pad_cella_sumout[63:63]),
	.dataa(1'b0),
	.datab(1'b0),
	.datac(1'b0),
	.datae(1'b0),
	.datag(1'b0),
	.sharein(1'b0)
	);
	defparam
		pad_cella_63.extended_lut = "off",
		pad_cella_63.lut_mask = 64'h000000FF0000FF00,
		pad_cella_63.shared_arith = "off",
		pad_cella_63.lpm_type = "stratixv_lcell_comb";
	assign
		wire_pad_cella_datad = {add_sub_cell_ffa};
	assign
		result = pad_cell_ffa[63:0];
endmodule //addfix8_add_sub
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module addfix8 (
	clock,
	dataa,
	datab,
	result)/* synthesis synthesis_clearbox = 1 */;

	input	  clock;
	input	[63:0]  dataa;
	input	[63:0]  datab;
	output	[63:0]  result;

	wire [63:0] sub_wire0;
	wire [63:0] result = sub_wire0[63:0];

	addfix8_add_sub	addfix8_add_sub_component (
				.clock (clock),
				.dataa (dataa),
				.datab (datab),
				.result (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: CarryIn NUMERIC "0"
// Retrieval info: PRIVATE: CarryOut NUMERIC "0"
// Retrieval info: PRIVATE: ConstantA NUMERIC "0"
// Retrieval info: PRIVATE: ConstantB NUMERIC "0"
// Retrieval info: PRIVATE: Function NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix V"
// Retrieval info: PRIVATE: LPM_PIPELINE NUMERIC "2"
// Retrieval info: PRIVATE: Latency NUMERIC "1"
// Retrieval info: PRIVATE: Overflow NUMERIC "0"
// Retrieval info: PRIVATE: RadixA NUMERIC "10"
// Retrieval info: PRIVATE: RadixB NUMERIC "10"
// Retrieval info: PRIVATE: Representation NUMERIC "0"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: ValidCtA NUMERIC "0"
// Retrieval info: PRIVATE: ValidCtB NUMERIC "0"
// Retrieval info: PRIVATE: WhichConstant NUMERIC "0"
// Retrieval info: PRIVATE: aclr NUMERIC "0"
// Retrieval info: PRIVATE: clken NUMERIC "0"
// Retrieval info: PRIVATE: nBit NUMERIC "64"
// Retrieval info: PRIVATE: new_diagram STRING "1"
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: CONSTANT: LPM_DIRECTION STRING "ADD"
// Retrieval info: CONSTANT: LPM_HINT STRING "ONE_INPUT_IS_CONSTANT=NO,CIN_USED=NO"
// Retrieval info: CONSTANT: LPM_PIPELINE NUMERIC "2"
// Retrieval info: CONSTANT: LPM_REPRESENTATION STRING "SIGNED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_ADD_SUB"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "64"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL "clock"
// Retrieval info: USED_PORT: dataa 0 0 64 0 INPUT NODEFVAL "dataa[63..0]"
// Retrieval info: USED_PORT: datab 0 0 64 0 INPUT NODEFVAL "datab[63..0]"
// Retrieval info: USED_PORT: result 0 0 64 0 OUTPUT NODEFVAL "result[63..0]"
// Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: @dataa 0 0 64 0 dataa 0 0 64 0
// Retrieval info: CONNECT: @datab 0 0 64 0 datab 0 0 64 0
// Retrieval info: CONNECT: result 0 0 64 0 @result 0 0 64 0
// Retrieval info: GEN_FILE: TYPE_NORMAL addfix8.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL addfix8.inc TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL addfix8.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL addfix8.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL addfix8_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL addfix8_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL addfix8_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
