`timescale 1ns / 1ns

// Amir Alizadeh created at Nottingham Trent University.
module gen_cost_tb ();


// Declare signals to connect to the UART module
reg RST;
reg CLK;

parameter CLOCKWIDTH = 2;
parameter CLOCKWIDTH_HALF = 1;
parameter CLOCKWIDTH50 =  CLOCKWIDTH*50; // 50 cycles
parameter WAITINTERVAL =  CLOCKWIDTH*100; // 100 cycles
parameter P=64;
parameter samples = 5;
localparam N = 1 + 185 + 1; // latency of whole pipline  cordic and multiplier and slicer

// DUT signal
reg  [P-1:0]  gamma; // gamma
reg  [P-1:0]  H;     // sin beta
reg  [P-1:0]  exact_sol_cos; // exact result
reg  [P-1:0]  exact_sol_sin; // exat result from python

wire signed [P-2:0]  Hr_o; 
wire signed [P-2:0]  Hi_o;


wire int_sin_sign = Hi_o[P-1]; 
wire [2:0] int_sin = Hi_o[P-1:60]; // 3 int part
wire [60:0] frac_sin = Hi_o[60:0]; // 61 frac part


//  DUT instantiation
gen_cost #(.P(P)) cogen (
   
   .CLK(CLK),
   .RST(RST),
   .gamma(gamma), // cos gamma
   .H(H),
   .Hr_o(Hr_o),
   .Hi_o(Hi_o)
);


always #CLOCKWIDTH_HALF CLK <= ~CLK;
integer i;

// initialasation
initial begin 
      CLK <0;
      RST <= 1;
      gamma <= 64'h0;
      H <= 64'h0;
      i <= 0;
      #CLOCKWIDTH;

      // apply 10 cycle 
      repeat (10) @(posedge CLK);
      RST <= 0;

      @(posedge CLK);
      gamma <=  64'hed83105a46afb400;  
      H <= 64'hfcf0c4e6380d7400; 
      repeat (N+10) begin
            @(posedge CLK);
      i <= i+1;
      end
      $stop;

end
endmodule



/*
// expected data in simulation


logic [63: 0] data [samples-1:0]; 
logic [63: 0] costF [2*samples-1:0]; // expected output {cos0, sin0, cos1, sin1, ....} (10 values)

// result from pipline 
reg [63:0] sol_ar_Pipe [0:N-1]; // rgister to store the real part of solution
reg [63:0] sol_ai_Pipe [0:N-1]; // register for imaginary part
wire [63:0] sol_cos_out = sol_ar_Pipe[N-1];
wire [63:0] sol_sin_out = sol_ai_Pipe[N-1];


//`include "gen_cost_tb_in.sv" // include the stimulus data generated by gen_cost_input.py
//data = data_sample;
//costF = costF_sample;
//gamma = gamma_data;
initial begin
      
// initilise 
//test data - (Fixed-point-Q2.61 format (1 bit sin - 1 bit integer - 61 fraction)) - Range [-2, 2) 
gamma = 64'h1cbafac65bb08c00;data = {64'h16c6b9b4f03aee00, 64'h1391cee3c778fa00, 64'h020b57a2ccc02400, 64'hea96fe27a7f2f200, 64'hecd056a657be2800};costF = {64'h19af7d61817b1000, 64'h1315e09f7e385c00, 64'h1b4be31faa81ff00, 64'h10b34ffc046e5500, 64'h1ff2874c24eecc00, 64'h01d59cafad21d020, 64'h1a65e1d2024e6900, 64'hede9ad3fa4e3c200, 64'h1b797857aababf00, 64'hef981985f9308300};

      RST <= 1; // Reset active-high
      CLK <= 1;
      // Apply reset
      #CLOCKWIDTH50;
      RST <= 0;


      for (i = 0; i < NPip; i = i + 1) begin
            sol_ar_Pipe[i] <= 0;
            sol_ai_Pipe[i] <= 0;
      end

      #CLOCKWIDTH50;
      #CLOCKWIDTH50;
      
      for (i = 0; i <samples ; i = i + 1) begin
            H <= data[i];
            exact_sol_cos <= costF[i*2 + 0]; // this is exact solution [cosi, sin,cso2,sin2,....]
            exact_sol_sin <= costF[i*2 + 1]; //  this is exact solution [cosi, sin,cso2,sin2,....]
            #CLOCKWIDTH;
      end

      for(i=0;i<NPip;i=i+1) begin
            exact_sol_cos <= 0;
            exact_sol_sin <= 0;
            H <= '0;
            #CLOCKWIDTH;
      end
      #WAITINTERVAL;

      $stop;
end

always
begin
      #CLOCKWIDTH_HALF;
      CLK <= ~CLK; // clock generation, half period
end
integer j;
always @(posedge CLK) begin
      
      sol_ar_Pipe[0] <= exact_sol_cos;
      sol_ai_Pipe[0] <= exact_sol_sin;
      for (j = 0;j < NPip-1; j = j + 1) begin
            sol_ai_Pipe[j+1] <= sol_ai_Pipe[j];
            sol_ar_Pipe[j+1] <= sol_ar_Pipe[j];
      end
end
endmodule
*/