// CORDIC_64_fixedP.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module CORDIC_64_fixedP (
		input  wire [63:0] a,      //      a.a
		input  wire        areset, // areset.reset
		output wire [62:0] c,      //      c.c
		input  wire        clk,    //    clk.clk
		output wire [62:0] s       //      s.s
	);

	CORDIC_64_fixedP_CORDIC_0 cordic_0 (
		.clk    (clk),    //    clk.clk
		.areset (areset), // areset.reset
		.a      (a),      //      a.a
		.c      (c),      //      c.c
		.s      (s)       //      s.s
	);

endmodule
